# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-06 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poloniex_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicredentials',
            old_name='hash',
            new_name='secret',
        ),
    ]
